exclude: "docs"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      -  id: pyupgrade
         args: [--py37-plus]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]

  - repo: https://github.com/crate-ci/typos
    rev: v1.24.5
    hooks:
      - id: typos
